### ISSUE TITLE
Several flash messages with PHP errors are shown if webtrees has no internet connection

### ISSUE THREAD

**Issue by Jefferson49** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#101]
Observed with webtrees 2.1.17 and vesta 2.1.17.0.0

If webtrees has no internet connection (e.g. webtrees running on NAS in internal network, but external network is disconnected), opening a webtrees page results in several flash messages, which include PHP error stacks. Seemingly, each vesta module creates a red flash message, which includes a stack trace.

Two of the stack traces, are included as attachements.

[Stack trace vesta without internet connection 1.txt](https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/files/12467358/Stack.trace.vesta.without.internet.connection.1.txt)
[Stack trace vesta without internet connection 2.txt](https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/files/12467359/Stack.trace.vesta.without.internet.connection.2.txt)

**Comment by ric2016** [comment]
Fixed in latest release 2.1.17.0.4.
