### ISSUE TITLE
Move wt-icon-map-gov in line with the wt edit icons

### ISSUE THREAD

**Issue by HerzScheisse** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#108]
Hi,

Just another minor style change suggestion...

Is it possible to move the "reload GOV data" icon in line with the other icons? Dont know how difficult it is to implement this and to work with any other modules in general... but this would save up a bit of space... the only thing that is display in the right column is the GOV ID

What do you think?

![gov reload old](https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/assets/146635896/fd08d7e5-c935-4742-8ad8-6a3729e9a560)

**Comment by ric2016** [comment]
No, that's not easily possible; actually I think it used to be there, but that was problematic for other custom modules that add edit links there.
Anyway it shouldn't take up additional space in general (only on the shared places page).

**Comment by HerzScheisse** [comment]
Okay... no problem.... I thought this might cause errors to other modules...
In favor to others modules i can live with that...
