### ISSUE TITLE
Sporadic errors: Integrity constraint violation / Duplicate entry

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#15]
From time to time there are errors like this:
![Screenshot (111)](https://user-images.githubusercontent.com/6324175/85839016-b18ee500-b79a-11ea-93fe-3177e7289eef.png)

After refresh of the browser window, they disappear for a while.

**Comment by ric2016** [comment]
I have seen this occasionally as well. I think this will have to be handled in webtrees itself, but I'll look into it further.

**Comment by ric2016** [comment]
I'm closing this - I think this will have to be handled by webtrees itself.
