### ISSUE TITLE
_GOV id changed

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#19]
Whenever I edit a record like
```
1 RESI
2 DATE FROM 01 AUG 2012 TO 31 AUG 2016
2 PLAC Wedding, Mitte, Berlin, DEU
3 _GOV WEDINGJO62QM
```

and do not touch the _GOV record, then the GOV identifier is afterwards changed:
```
1 RESI
2 DATE FROM 01 AUG 2012 TO 1 SEP 2016
2 PLAC Wedding, Mitte, Berlin, DEU
3 _GOV @WEDINGJO62QM@
```

"@WEDINGJO62QM@" is wrong.

**Comment by ric2016** [comment]
This error originates from webtrees itself, where very basic _GOV support has been added some time ago (disabling the Vesta modules does not change the behavior).

[This line](https://github.com/fisharebest/webtrees/blob/602c43e8028b434b2e8a836fc236284708cf3401/app/Functions/FunctionsEdit.php#L326) handles _GOV as an internal link, which is wrong.

**Comment by hartenthaler** [comment]
You are right about not to use "_GOV" in single event places, but I have already a lot of them. As soon as my hirarchical shared place structure will be perfect, I will delete these _GOV records all.

Thanks for forwarding this issue.

**Comment by ric2016** [comment]
Fixed in Vesta, and in webtrees.
