### ISSUE TITLE
Width of gov-id control in Set/Reset GOV-ID form

### ISSUE THREAD

**Issue by bschwede** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#29]
In "Facts and events"-tab the gov-id control shown in modal dialog box renders too narrow, when no id is set.
![Screenshot GOV-ID control](https://user-images.githubusercontent.com/14359683/103300125-74800580-49fe-11eb-96f2-cb5535911db6.png)

__Fix-Suggestion:__ Appending something like `span#select2-gov-id-container {min-width:250px;}` in [resources/css/webtrees.css](https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/blob/master/resources/css/webtrees.css) - is it also necessary to be added in minimal.css?!.

__Setup:__ webtrees=2.0.10 (with webtrees theme) // vesta-mods=2.0.10.4.0 // tested with firefox=84.0.1 and chrome=87.0.4280.88

**Comment by ric2016** [comment]
I cannot reproduce this - Do you use any other custom css, or other custom modules?

Do you see this effect [on the demo server](https://cissee.de/gov4webtrees2Demo/tree/demo/individual/I273/Heinrich%20Wilhelm%20M%C3%BCller%20%5BEitze%5D)?

Do you have a public tree where I can see this?

**Comment by bschwede** [comment]
Unfortunately I don't have a public tree so far. My stack was a fresh install for migrating from webtrees version 1.7.x.
I don't use any other custom css. I just tested "Vesta Classic Look & Feel" - but it doesn't vary when options there were activated or not.

Difference between demo-server [1] and my local stack [2] I noticed: Width of element `span.select2.select2-container.select2-container--default.select2-container--below.select2-container--focus` is set to an explicit px-value [1] ([2] = auto).

active modules:
- vesta_classic_look_and_feel
- vesta_common
- vesta_extended_relationships
- vesta_gov4webtrees
- vesta_location_data
- vesta_personal_facts
- vesta_places_and_pedigree_map
- vesta_relatives
- vesta_research_suggestions.disable
- vesta_shared_places
- nothing else

Maybe it's fate of a single person.

**Comment by ric2016** [comment]
Without fully understanding the select2 width resolution, I notice that webtrees explicitly sets `style="width:100%"` for its select components - So I'm doing that as well now for this component.

Can you check [whether the change from this commit](https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/commit/b4b5233ddea4b666ccaee4b47055b20f4f3c6ac0) resolves this issue for you?

**Comment by bschwede** [comment]
This did the trick :-)

Thanks for your support and those cool modules! Happy new year.

**Comment by ric2016** [comment]
Thank you for the feedback - I'll have the next release ready shortly.

**Comment by ric2016** [comment]
Fixed in latest release.
