### ISSUE TITLE
wrong remark "place is not existing"

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#43]
Why is in the following case "Tsingtau" not existing at that time (1901 is between 1898 and 1919)?

![Screenshot (333)](https://user-images.githubusercontent.com/6324175/119352559-20720800-bca2-11eb-817d-eb7d9b96617b.png)

Quicktext:
![Screenshot (334)](https://user-images.githubusercontent.com/6324175/119352609-31227e00-bca2-11eb-92de-57689ff1af4a.png)

**Comment by ric2016** [comment]
"Kolonie (Überseegebiet)" ist a newly introduced type (277), which Vesta doesn't know yet.
I'll handle unknown types differently, and I'll upgrade the type definitions in the next release.

**Comment by ric2016** [comment]
Fixed and new type added in Release 2.0.16.1.1.
