### ISSUE TITLE
"this place does not exist at that point of time"

### ISSUE THREAD

**Issue by fasal13** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#55]
Ich bekomme das ziemlich häufig angezeigt, auch wenn ich im Quicktext bei GOV keinen direkten Grund sehe. Beispiel:

STAICEJO90HH
	has 1939 population 1602,
	has external reference SIMC:0940111,
	has external reference geonames:8426597,
	has from 1945 name (in pol) Stare Gliwice,
	has name (in pol) Stare Gliwice,
	**has until 1945 name (in deu) Alt Gleiwitz,**
	is 2015 (in deu) Stadtteil,
	is part of object_1073758 says source_1079298,
	located at 50.3117°N 18.6239°O;

Oder kommt das weil der Bezug auf object_1073758 liegt, in dem dies anscheinend nicht vollständig erfasst ist?
Fehler in go4webtrees oder in GOV?

**Comment by ric2016** [comment]
Das ist schlecht modelliert im GOV, dort steht nur "is 2015 (in deu) Stadtteil", aber was ist in allen Jahren != 2015?

**Comment by fasal13** [comment]
Kann sich die Interpretation nicht auch auf "name" beziehen? Das wird deutlich besser gepflegt.

**Comment by ric2016** [comment]
Ich sehe nicht, wie das gehen soll: Der Name gibt ja keinen Aufschluß bzgl. des Objekttypen(*). Der sollte schon über den gesamten Zeitraum angegeben werden im GOV aus meiner Sicht, das wird in anderen Regionen ja auch gemacht.

Ich möchte grundsätzlich nicht die schlechte Modelliering im GOV noch durch Workarounds unterstützen, da muß einfach verbessert werden und bessere Qualitätssicherung eingebaut werden.

(*) Hier ein Beispiel, warum die korrekte Angabe des Typen über einen Zeitraum wichtig ist:
http://gov.genealogy.net/item/show/object_1087147
Dieser Ort existiert tatsächlich nur bis 1936, unabhängig von seinem Namen.
