### ISSUE TITLE
Questions to "Show changes in GOV hierarchy"

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#79]
On my page I have two problems with this new feature. (https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/issues/76)

1. It is not possible to turn off the display of the GOV Hierarchy
2. The place name from shared places is displayed and not the names from GOV.

![image](https://user-images.githubusercontent.com/60657963/166325884-12b7637e-1797-42a6-af53-49fa4a27394b.png)

http://gov.genealogy.net/item/show/TRNAVAJN88TJ

**Comment by ric2016** [comment]
I can confim the toggle checkbox doesn't work currently - oops.

Apart from that, the list is supposed to look like this though (i.e. same formatting for GOV as elsewhere):
No sure why the GOV hierarchy isn't shown in your case. Does it work for 'regular' facts (on the facts & events tab?)
<img width="647" alt="GOV" src="https://user-images.githubusercontent.com/18174787/166328995-01efd38b-4d99-4d08-93f6-7a785ac78ae2.png">

**Comment by ro-la** [comment]
Closing this Issue - the follow up is in [#79](https://github.com/vesta-webtrees-2-custom-modules/vesta_gov4webtrees/issues/79) and [#120](https://github.com/vesta-webtrees-2-custom-modules/vesta_shared_places/issues/120)
