### ISSUE TITLE
Error when GOV server not online (reachable)

### ISSUE THREAD

**Issue by ro-la** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#8]
From time-to time is the GOV-server not reachable (now 2020-03-30 16:51 CEST). Perhaps something on the Schengen-border :-)

the vesta Fact&Event tab is diplaying only following errors:
`Error Fetching http headers …/modules_v4/vesta_gov4webtrees/FunctionsGov.php:94
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://gov.gene...', '', 1, 0)
#1 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(94): SoapClient->__call('checkObjectId', Array)
#2 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(858): Cissee\Webtrees\Module\Gov4Webtrees\SoapWrapper::checkObjectId(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), 'TRNAVAJN88TJ')
#3 …/modules_v4/vesta_gov4webtrees/FunctionsGov.php(1025): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::loadGovObject(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), 'TRNAVAJN88TJ')
#4 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(629): Cissee\Webtrees\Module\Gov4Webtrees\FunctionsGov::retrieveGovObjectSnapshot(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), '2406294', 'TRNAVAJN88TJ', -1, 'sk', false)
#5 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(551): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->getDataAndNextId(true, 'sk', '2406294', 'TRNAVAJN88TJ', -1, false)
#6 …/modules_v4/vesta_gov4webtrees/Gov4WebtreesModule.php(521): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->getHierarchy(true, true, 'sk', '2406294', '1876', 'TRNAVAJN88TJ', 'shared place vi...', false)
#7 …/modules_v4/vesta_personal_facts/FunctionsPrintWithHooks.php(54): Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule->factPlaceAdditions(Object(Vesta\Model\PlaceStructure))
#8 [internal function]: Cissee\Webtrees\Module\PersonalFacts\FunctionsPrintWithHooks->Cissee\Webtrees\Module\PersonalFacts\{closure}(Object(Cissee\Webtrees\Module\Gov4Webtrees\Gov4WebtreesModule), '_vesta_gov4webt...')
#9 …/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array)
#10 …/modules_v4/vesta_personal_facts/FunctionsPrintWithHooks.php(55): Illuminate\Support\Collection->map(Object(Closure))
#11 …/modules_v4/vesta_personal_facts/patchedWebtrees/Functions/FunctionsPrint_2x.php(59): Cissee\Webtrees\Module\PersonalFacts\FunctionsPrintWithHooks->formatPlaceNameAndSubRecords(Object(Vesta\Model\PlaceStructure))
#12 …/modules_v4/vesta_personal_facts/patchedWebtrees/Functions/FunctionsPrintFacts_2x.php(462): Cissee\WebtreesExt\Functions\FunctionsPrint_2x->formatFactPlace(Object(Fisharebest\Webtrees\Fact), true, true, true)
#13 …/modules_v4/vesta_personal_facts/patchedWebtrees/Module/IndividualFactsTabModule_2x.php(152): Cissee\WebtreesExt\Functions\FunctionsPrintFacts_2x->printFactAndReturnScript(Object(Fisharebest\Webtrees\Fact), Object(Fisharebest\Webtrees\Individual))
#14 …/modules_v4/vesta_personal_facts/resources/views/tab.phtml(51): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x->Cissee\WebtreesExt\Module\{closure}(Object(Fisharebest\Webtrees\Fact))
#15 …/app/View.php(186): include('/home/html/just...')
#16 …/app/View.php(282): Fisharebest\Webtrees\View->render()
#17 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make('_vesta_personal...', Array)
#18 …/modules_v4/vesta_personal_facts/patchedWebtrees/Module/IndividualFactsTabModule_2x.php(157): view('_vesta_personal...', Array)
#19 …/app/Module/ModuleTabTrait.php(140): Cissee\WebtreesExt\Module\IndividualFactsTabModule_2x->getTabContent(Object(Fisharebest\Webtrees\Individual))
#20 …/app/Http/RequestHandlers/ModuleAction.php(90): Cissee\Webtrees\Module\PersonalFacts\IndividualFactsTabModuleExtended->getTabAction(Object(Nyholm\Psr7\ServerRequest))
#21 …/app/Http/Middleware/WrapHandler.php(83): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle(Object(Nyholm\Psr7\ServerRequest))
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\WrapHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#23 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#25 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#28 …/app/Http/Middleware/Router.php(134): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/BootModules.php(62): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/app/Http/Middleware/LoadRoutes.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#35 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#36 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 …/app/Http/Middleware/DoHousekeeping.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 …/app/Http/Middleware/UseTheme.php(70): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#42 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 …/app/Http/Middleware/UseLanguage.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 …/app/Http/Middleware/UseSession.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 …/app/Http/Middleware/UseFilesystem.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseFilesystem->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 …/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 …/app/Http/Middleware/UseDatabase.php(106): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 …/app/Http/Middleware/BadBotBlocker.php(208): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 …/app/Http/Middleware/UseCache.php(74): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseCache->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#60 …/vendor/middlewares/client-ip/src/ClientIp.php(81): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#61 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#63 …/app/Http/Middleware/HandleExceptions.php(76): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#65 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#67 …/app/Http/Middleware/ReadConfigIni.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#68 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#69 …/app/Http/Middleware/SecurityHeaders.php(47): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#70 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#71 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#72 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#73 …/app/Http/Middleware/PhpEnvironment.php(49): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#74 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\PhpEnvironment->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#75 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#76 …/index.php(55): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#77 {main}`

Ladislav

**Comment by ric2016** [comment]
There isn't much we can do about temporary GOV-Server issues.
But we should produce better error messages, without disrupting the rest of webtrees.

It's a tricky to test this, unfortunately, as the GOV-Server is usually available - I guess I'll have to set up a faulty SOAP server myself.

**Comment by ric2016** [comment]
By the way, one possible cause for these errors may be a small value for the php setting 'default_socket_timeout', in connection with an occasionally slow GOV-Server. You can check this value e.g. via the Control Panel ('Server information'). If you have set it to something like 60 (seconds) though, it is likely a different issue. If it is much smaller than that, it may help to increase it.

**Comment by ro-la** [comment]
My default_socket_timeout is set to 60.

And when this error was displayed it was not possible to display any page from genealogy.net. From my view it was a shutdown of the whole website genealogy.net for about 30-60 minutes.

**Comment by ric2016** [comment]
I thought so, just wanted to make sure. I'll fix this and provide a proper error message in this case.

**Comment by ric2016** [comment]
Also occurs with different error message, see [here](https://www.webtrees.net/index.php/en/forum/4-customising/34355-vesta-gov4webtrees-2-0-3-7).
We should probably just catch any Exception here.

**Comment by ric2016** [comment]
Fixed in latest release.
