### ISSUE TITLE
Tab "Place history" uses only current GOV hierarchy

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#80]
The "GOV Hierarchy" entries in the "Place history" are great! Thank you! But they are showing always the GOV hierarchy of today. This is independent of the configuration in control panel.

I would prefer to see the hierarchy at the time a "GOV Hierarchy" entry belongs to.
![Screenshot (127)](https://user-images.githubusercontent.com/6324175/166330407-4c2915e5-f70c-46ae-9c44-fa8984dbc1eb.png)

**Comment by ric2016** [comment]
Fixed in patch release 2.1.1.0.1.
