### ISSUE TITLE
Show GOV object type in customer language instead of English

### ISSUE THREAD

**Issue by hartenthaler** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#88]
When showing a shared location the GOV object type is displayed always in English. I would prefer to see it in the language of my browser (ie German in my case: "Weiler" instead of "hamlet").

> Weiler
> GOV-Kennung für die Art des Ortes: hamlet — 69

**Comment by ric2016** [comment]
Fixed in code (already worked for the selection dropdown when editing).
Note that, as usual in webtrees, the webtrees language is used rather than the browser language. 

Vesta release to follow.
