### ISSUE TITLE
GOV-Id Modal: Select2 does not always initialize

### ISSUE THREAD

**Issue by ric2016** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#9]
See screenshot. Other select2 components seem to work.

![image](https://user-images.githubusercontent.com/18174787/78536654-7c53a600-77ee-11ea-969f-1d13ea274499.png)

Occurs at <https://www.genealogie-roy-ramet.com/tree/roy-ramet/individual/X5456/Antoinette%20BOST>

Refactor the initialization logic closer to regular modals/ select2 components.

**Comment by ro-la** [comment]
Just for protocol very similary/the same problem in webtrees: https://github.com/fisharebest/webtrees/issues/2935

**Comment by ric2016** [comment]
Fixed in the latest release.

**Comment by ric2016** [comment]
Still buggy for edit control within other modals ("Create Shared Place").

**Comment by ric2016** [comment]
To summarize, the custom select2 control is used in 3 different contexts:

* When a GOV-Id of a shared place is edited, as a fact (non-modal)
* When a GOV-Id is edited via the facts & events tab (within its own modal)
* When a GOV-Id is set when creating a new shared place (within the shared place's modal)

The latter two require a custom modal placeholder (default placeholder would be webtrees' ajax.phtml) which allows the initialization of custom select2 controls (ajax-modal-vesta.phtml, in vesta-common).

**Comment by ric2016** [comment]
Finally fixed in latest release.

**Comment by ric2016** [comment]
Again: Still buggy for edit control within other modals ("Create Shared Place").
(see https://github.com/ric2016/shared_places/issues/8)

**Comment by ric2016** [comment]
Finally (hopefully!) fixed in latest release.
