### ISSUE TITLE
_GOV in facts and events

### ISSUE THREAD

**Issue by webtrees-pesz** [vesta-webtrees-2-custom-modules/vesta_gov4webtrees#97]
How do I make the field for GOV ID visible for places in input forms if I have only GOV4webtrees enabled but not the module for SharedPlaces?

Best regards, Peter

**Comment by ric2016** [comment]
This use case isn't supported by the Gov4Webtrees module. 

A default edit control should be available when activating the Gecom-L tags in the control panel, but this only works for existing _GOV subtags (this part is a webtrees bug).

In any case eabling or disabling Shared Places does not affect how  3 _GOV under 2 PLAC is handled, nor should it.
